### ISSUE TITLE
Mongodb required for local installation?

### ISSUE THREAD

**Issue by dhirensr** [zdresearch/OWASP-Honeypot#4]
in the wiki docs I saw nowhere in the installation tab about mongodb installation,and when you locally install the other packages and run "python ohp.py" it gives you an error after the logo saying that cannot connect to mongodb.
If Mongodb is required it should be mentioned in the installation ! I would like to change the docs once @Ali-Razmjoo  replies for further clarification!

Please review the 2 tickets i have created! @Ali-Razmjoo

**Comment by Ali-Razmjoo** [comment]
Hi again,

thanks for your feedback on the wiki, I will try to clear things up in next weekend.

regards.

**Comment by tulja** [comment]
@dhirensr MongoDB is installation is required for ohp.py.And it needs to separately run alongside the ohp.py. Since, in the core/load.py (in check_for_requirements()) tries to connect to MongoDB via pymongo client. 
You can refer to [this](https://www.digitalocean.com/community/tutorials/how-to-install-mongodb-on-ubuntu-16-04) for installation and setup on Ubuntu 16.04.

**Comment by dhirensr** [comment]
@tulja  : i have configured it already on my local machine! the docs of the project does not mention this thats what the question was! please read the last line for the ticket ,i have mentioned that it should be there in the wiki!
thanks for the reply!

**Comment by Ali-Razmjoo** [comment]
I've already added that you need to install MongoDB, but since our users may use a different OS than Ubuntu, I am not sure if I should share specific URL for that.

https://github.com/zdresearch/OWASP-Honeypot/wiki/Installation

@tulja @dhirensr  thanks for your feedbacks 👍  looking forward to hearing more from you
